autodock:
    executable: ./autodock_vina/bin/vina
    num_modes: 9
    seed: 1

dataset:
    name: pl
    path: ./dataset/crossdocked_pocket10
    split: ./dataset/split_by_name.pt
    
featuriser:
    interaction_cutoff: 4.0
    sasa_cutoff: 4.0
    symbol_radius_path: ./config/symbol_radius.json

general:
    MAX_INT: 2147483647
    seed: 1
