dataset:
    path: ./dataset/crossdocked_graph10
    split: ./dataset/split_by_name.pt
    
embedding:
    atomic_distance_cutoff: 4.0
    batch_size: 64
    dropout: 0.13
    heads: 2
    hetero_aggr: mean
    hidden_channels_la: 
    - 48
    - 76
    - 121
    hidden_channels_pa:
    - 48
    - 57
    - 68
    lr: 0.001
    mlp_channels:
    - 1
    - 189
    - 256
    molecular_embedding_size: 4
    num_layers: 3
    str_for_hparams: 'InterMol length: 4.0A'
    weight_decay: 0.0001

model:
    name: SINGA
