dataset:
    path: ./dataset/crossdocked_graph10_v2
    split: ./dataset/split_by_name.pt
    atomic_distance_cutoff: 4.0
    
dataloader:
    atomic_distance_cutoff: 4.0
    batch_size: 64
    molecular_embedding_size: 4
    num_workers: 1

embedding:
    edge_channels: 16
    sphere_channels: 16
    attn_hidden_channels: 128
    attn_alpha_channels: 32
    attn_value_channels: 16
    ffn_hidden_channels: 512
    lmax_list:
    - 6
    mmax_list:
    - 2
    cutoff: 10.0
    max_num_elements: 43
    num_heads: 7
    num_layers: 3
    norm_type: 'rms_norm_sh'
    activation_type: 'scaled_silu'
    use_atom_edge_embedding: True
    share_atom_edge_embedding: True
    grid_resolution: None
    alpha_drop: 0.0
    proj_drop: 0.0
    drop_path_rate: 0.0
    
model:
    name: SINGA
