dataset:
    name: pl
    path: ./dataset/crossdocked_vina10
    split: ./dataset/split_by_name.pt
    
model:
    name: singa
    
train:
    seed: 1
    use_apex: False
    batch_size: 8
    num_workers: 8
    pin_memory: True
    max_iters: 500000
    val_freq: 5000
    pos_noise_std: 0.1
    max_grad_norm: 100.0
    optimizer:
        type: adam
        lr: 2.e-4    
        weight_decay: 0
        beta1: 0.99
        beta2: 0.999
    scheduler:
        type: plateau
        factor: 0.6
        patience: 8
        min_lr: 1.e-5
    transform:
        mask:
            type: mixed
            min_ratio: 0.0
            max_ratio: 1.1
            min_num_masked: 1
            min_num_unmasked: 0 
            p_random: 0.15
            p_bfs: 0.6
            p_invbfs: 0.25
        contrastive:
            num_real: 20
            num_fake: 20
            pos_real_std: 0.05
            pos_fake_std: 2.0
        edgesampler:
            k: 8

PLInteraction:
    nonpolar:
        6: 1.7
        9: 1.47
        17: 1.75
        35: 1.85
        53: 1.98
    hbond_dist_cut: 3.5
    hbond_angle_cut: 180.0
    hbond_dist_bound: 2.5
    hbond_angle_bound: 90.0
    hphob_dist_cut: 4.0
    hphob_dist_bound: 1.25
    contact_scale_cut: 1.75
    contact_scale_opt: 1.25
    sbridge_dist_cut: 5.0
    sbridge_dist_bound: 3.25
    sbridge_resonance: True
    pistack_dist_cut: 6.5
    pistack_dist_bound: 3.8
    pistack_angle_cut: 90.0
    pistack_angle_boundL 60.0
    pication_dist_cut: 6.5
    pication_dist_bound: 4.3
    pication_angle_cut: 90.0
    pication_angle_bound: 30.0
    xbond_dist_cut: 5.0
    xbond_dist_bound: 3.5
    xbond_angle_cut: 150.0
    xbond_angle_bound: 135.0
    acceptor_metal_dist_cut: 4.0
    pimetal_dist_cut: 5.0
    
